// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_adelie_core_configs();
RcppExport SEXP _rcpp_module_boot_adelie_core_constraint();
RcppExport SEXP _rcpp_module_boot_adelie_core_glm();
RcppExport SEXP _rcpp_module_boot_adelie_core_io();
RcppExport SEXP _rcpp_module_boot_adelie_core_matrix();
RcppExport SEXP _rcpp_module_boot_adelie_core_matrix_utils_blas();
RcppExport SEXP _rcpp_module_boot_adelie_core_solver();
RcppExport SEXP _rcpp_module_boot_adelie_core_state();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_adelie_core_configs", (DL_FUNC) &_rcpp_module_boot_adelie_core_configs, 0},
    {"_rcpp_module_boot_adelie_core_constraint", (DL_FUNC) &_rcpp_module_boot_adelie_core_constraint, 0},
    {"_rcpp_module_boot_adelie_core_glm", (DL_FUNC) &_rcpp_module_boot_adelie_core_glm, 0},
    {"_rcpp_module_boot_adelie_core_io", (DL_FUNC) &_rcpp_module_boot_adelie_core_io, 0},
    {"_rcpp_module_boot_adelie_core_matrix", (DL_FUNC) &_rcpp_module_boot_adelie_core_matrix, 0},
    {"_rcpp_module_boot_adelie_core_matrix_utils_blas", (DL_FUNC) &_rcpp_module_boot_adelie_core_matrix_utils_blas, 0},
    {"_rcpp_module_boot_adelie_core_solver", (DL_FUNC) &_rcpp_module_boot_adelie_core_solver, 0},
    {"_rcpp_module_boot_adelie_core_state", (DL_FUNC) &_rcpp_module_boot_adelie_core_state, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_adelie(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
